### ISSUE TITLE
Eraser Functionality

### ISSUE THREAD

**Issue by ramaranjandey** [iampawan/fluttersignatureview#2]
HI pavan ..how to erase the painting with an eraser ??? not like clearing the whole data at a time ......

**Comment by iampawan** [comment]
That will need more work but yes, it can be achieved for sure. I'll try to cover it in future perhaps.

**Comment by ramaranjandey** [comment]
okay thank you ... but do you have any idea like what to use ...so that i
can implement that.....any suggetion???

**Comment by ramaranjandey** [comment]
Hello Pavan Can we use curve clipping for eraser functionality ...
in drawing .
